-- Recipes rewritten for the real kitchen: air fryer + a pot for boiling.
-- The previous B1 method called for a microwave, which isn't available.

alter table public.meals
  add column if not exists prep_min  integer,
  add column if not exists cook_min  integer,
  add column if not exists equipment text,
  add column if not exists steps     text[],
  add column if not exists tips      text[];

update public.meals set prep_min=10, cook_min=12, equipment='Air fryer + small pot', steps=array['Boil 250ml water, stir in 60g oats and simmer 4-5 min until thick. Cinnamon off the heat.','Whisk 3 eggs and 150g egg whites with salt and pepper in an oven-safe dish that fits your basket.','Air fry 180C for 8 min, stirring once at the 4 min mark so the centre sets evenly.','Turn out onto the plate, oats alongside.'], tips=array['Fill the dish no more than two-thirds - the egg rises before it settles.','That stir at halfway is what prevents a rubbery edge with a raw middle.'] where code='B1' and user_id is null;
update public.meals set prep_min=5, cook_min=0, equipment='No cooking', steps=array['Stir 1 scoop of whey into 250g Greek yogurt a little at a time.','Slice the banana, crush 20g almonds, scatter both on top.'], tips=array['Adding the whey all at once makes it clump. Go in thirds.','A splash of water loosens it if the powder stiffens it too much.'] where code='B2' and user_id is null;
update public.meals set prep_min=5, cook_min=20, equipment='Air fryer + pot', steps=array['Rinse 80g dry basmati until the water runs clear, then boil 10-12 min and drain (makes ~220g cooked).','Coat the chicken in 15g olive oil, paprika, oregano and salt.','Air fry 195C for 18 min, flipping at 10 min.','Rest 3 min before slicing.'], tips=array['Pull the chicken at 74C internal. Overcooked breast is the difference between eating this happily for 90 days and dreading it.','Resting keeps the juice in the meat instead of on the board.'] where code='L1' and user_id is null;
update public.meals set prep_min=8, cook_min=22, equipment='Air fryer', steps=array['Cube 300g sweet potato to roughly 2cm and toss in half the oil.','Air fry 200C for 20 min, shaking the basket at 10 min.','Toss the turkey in the rest of the oil with herbs and salt.','Air fry 185C for 16 min. If your basket is small, do the potatoes first and let them rest while the turkey cooks.'], tips=array['Pat the cubes dry before oiling. Surface water steams instead of crisping.','Crowding is the enemy - a single layer beats a full basket every time.'] where code='L2' and user_id is null;
update public.meals set prep_min=2, cook_min=0, equipment='No cooking', steps=array['Shake 1 scoop of whey with cold water.','Eat the apple or banana alongside.'], tips=array['Cold water and a hard 10-second shake kills the foam.'] where code='S1' and user_id is null;
update public.meals set prep_min=3, cook_min=0, equipment='No cooking', steps=array['Stir 15g honey through 200g cottage cheese.','Top with 150g berries and 10g crushed almonds.'], tips=array['Frozen berries work and cost less - let them sit 5 min and they release a syrup that sweetens the whole bowl.'] where code='S2' and user_id is null;
update public.meals set prep_min=5, cook_min=20, equipment='Air fryer', steps=array['Cube 280g potatoes and air fry 200C for 18 min, shaking at 9 min.','Pat the salmon dry, season, and lay it skin-side down.','Air fry 200C for 10 min, adding the veg for the last 6 min.'], tips=array['Salmon is moist at 52-55C internal, firm at 60C. It carries on cooking after it comes out.','Don''t oil the skin if you want it crisp - dry it instead.'] where code='D1' and user_id is null;
update public.meals set prep_min=5, cook_min=15, equipment='Air fryer + pot', steps=array['Boil 65g dry rice for 10-12 min (makes ~200g cooked) and drain.','Toss the beef strips and peppers in 15g oil with paprika and garlic.','Air fry 190C for 10 min, shaking at 5 min.'], tips=array['Single layer, or the strips steam grey instead of browning. Two batches beats one crowded one.','5% beef needs no extra fat in the basket - the oil is for the peppers.'] where code='D2' and user_id is null;
update public.meals set prep_min=5, cook_min=6, equipment='Pot', steps=array['Boil 200ml soy milk, stir in 45g oats and simmer 4 min.','Take it off the heat, then stir in 50g vegan protein.','Top with 15g tahini.'], tips=array['Protein powder hitting boiling liquid seizes into lumps. Always off the heat.','Tahini on top, not stirred in - it turns bitter with prolonged heat.'] where code='BF1v2' and user_id is null;
update public.meals set prep_min=8, cook_min=14, equipment='Air fryer + pot', steps=array['Drain 250g chickpeas and dry them thoroughly on a towel.','Toss in 10g olive oil with cumin, paprika and salt.','Air fry 190C for 12 min, shaking twice.','Boil 150g edamame for 4 min and salt them. Bread on the side.'], tips=array['Drying the chickpeas is the whole trick. Wet ones never crisp, however long you run the fryer.','They firm up as they cool - pull them a shade before they look done.'] where code='LF1v2' and user_id is null;
update public.meals set prep_min=3, cook_min=0, equipment='No cooking', steps=array['Stir 35g vegan protein into 200g soy yogurt.','Eat the apple alongside.'], tips=array['Vegan protein thickens more than whey. Loosen it with water to a spoonable texture.'] where code='SF1v2' and user_id is null;
update public.meals set prep_min=3, cook_min=0, equipment='Blender or shaker bottle', steps=array['Blend 40g vegan protein, 250ml soy milk and 1 banana with ice.','No blender: shake hard in a bottle and eat the banana on the side.'], tips=array['A frozen banana thickens it without ice watering it down.','Good straight after training on a fasting day - it is the fastest protein in the plan.'] where code='SF2' and user_id is null;
update public.meals set prep_min=18, cook_min=15, equipment='Air fryer + pot', steps=array['Press 250g firm tofu for 15 min - wrap it in a towel with something heavy on top.','Cube it and toss with a spoon of cornflour, soy sauce and 5g oil.','Air fry 200C for 15 min, shaking at 8 min.','Warm 200g lentils in a pot while it cooks.'], tips=array['Cornflour is what makes air-fried tofu genuinely crisp. Without it you just get hot tofu.','Pressing is not optional - water in the block turns the fryer into a steamer.'] where code='DF1v2' and user_id is null;
update public.meals set prep_min=5, cook_min=12, equipment='Air fryer + pot', steps=array['Boil 65g dry rice for 10-12 min and drain.','Pat 250g shrimp dry, toss in 10g oil with garlic powder and paprika.','Air fry 200C for 8 min.'], tips=array['Shrimp go from perfect to rubber in about 90 seconds. Pull them the moment they turn opaque and curl.','Frozen shrimp: thaw and dry completely first, or they poach in their own water.'] where code='DF2v2' and user_id is null;

update public.meals set instructions = array_to_string(steps, ' ') where steps is not null and user_id is null;
